### PR TITLE
Don't be evil. And if we ever remove this motto, it's because we are evil now.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by arthtyagi** [comment]
You shouldn't be shitposting on someone's repository by creating irrelevant PRs. Have some decency bruh.

**Comment by ghost** [comment]
It wasn't meant to be a shitpost, but I understand. I'll close it.

**Comment by geohot** [comment]
lol, this isn't shitposting. I would have merged this!

**Comment by arthtyagi** [comment]
lol fr? you're unpredictable xD, if I owned this repo which I don't, I would've never merged it.

**Comment by ghost** [comment]
lol chill it's just a PR

**Pull request closed without merging**
